# Generated by Django 3.0.14 on 2021-05-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='photo',
            new_name='image',
        ),
    ]
