# Generated by Django 3.0.14 on 2021-05-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20210501_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
