# Generated by Django 3.0.14 on 2021-05-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20210501_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='theme',
        ),
        migrations.AddField(
            model_name='list',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.Theme'),
            preserve_default=False,
        ),
    ]
